'use client';

import { useEffect, useMemo, useState } from 'react';
import { PLAYER_POOL } from './players.generated';
import { HISTORIC_PHOTOS } from './historic-photo-overrides';

type Pos='QB'|'RB'|'WR'|'TE'; type Pick='first'|'second'|'third'; type Tier='platinum'|'ruby'|'gold'|'emerald'|'silver'|'bronze';
type Player={id:string;name:string;pos:Pos;year:number;team:string;photo:string;points:number;tier:Tier;percentile:number;value:number};
type Slot={label:string;player:Player|null;locked?:boolean};
type Trade={id:number;pickLabel:string;pickValue:number;outgoing:Player|null;incoming:Player;pointsDelta:number;cvDelta:number};
const TIER_RANGES=[{tier:'platinum',label:'TOP 2%'},{tier:'ruby',label:'2—8%'},{tier:'gold',label:'8—20%'},{tier:'emerald',label:'20—40%'},{tier:'silver',label:'40—65%'},{tier:'bronze',label:'65—100%'}] as const;
const BASE=PLAYER_POOL.map(p=>({...p,pos:p.pos as Pos,photo:p.photo||HISTORIC_PHOTOS[p.name]||'',points:Number(p.points)}));
const GROUPS=Object.fromEntries((['QB','RB','WR','TE'] as Pos[]).map(pos=>[pos,BASE.filter(p=>p.pos===pos).map(p=>p.points)])) as Record<Pos,number[]>;
const PLAYERS:Player[]=BASE.map(p=>{const peer=GROUPS[p.pos];const pct=peer.filter(v=>v>p.points).length/peer.length*100;const tier:Tier=pct<2?'platinum':pct<8?'ruby':pct<20?'gold':pct<40?'emerald':pct<65?'silver':'bronze';return {...p,percentile:+pct.toFixed(1),tier,value:Math.round(12+(100-pct)*1.18)}});
const DEFAULT_SLOTS:Slot[]=['QB','RB','RB','WR','WR','TE','FLX','BENCH'].map(label=>({label,player:null,locked:label==='BENCH'}));
const PICK_INFO:{id:Pick;label:string;value:number;range:string;copy:string}[]=[
 {id:'first',label:'1ST ROUND',value:100,range:'+8 to +150 pts',copy:'Massive ceiling. Real bust risk vs. cost.'},
 {id:'second',label:'2ND ROUND',value:55,range:'+5 to +95 pts',copy:'Strong upside. A much shakier floor.'},
 {id:'third',label:'3RD ROUND',value:25,range:'+2 to +38 pts',copy:'Cheap gain. Lower ceiling, rare jackpot.'}
];
const PICK_CFG={first:{min:8,max:150,power:.65},second:{min:5,max:95,power:.95},third:{min:2,max:38,power:1.15}};
const RECORD_LADDER=[
 {min:1952.6,record:'17–0',percentile:'TOP 5%',title:'PERFECT DYNASTY'},
 {min:1883.0,record:'16–1',percentile:'TOP 10%',title:'LEAGUE JUGGERNAUT'},
 {min:1778.8,record:'15–2',percentile:'TOP 18%',title:'TITLE FAVORITE'},
 {min:1717.9,record:'14–3',percentile:'TOP 28%',title:'CHAMPIONSHIP CONTENDER'},
 {min:1641.1,record:'13–4',percentile:'TOP 40%',title:'DIVISION CHAMPION'},
 {min:1603.5,record:'12–5',percentile:'TOP 52%',title:'PLAYOFF LOCK'},
 {min:1520.6,record:'11–6',percentile:'TOP 64%',title:'PLAYOFF TEAM'},
 {min:1473.7,record:'10–7',percentile:'TOP 74%',title:'WILD-CARD TEAM'},
 {min:1408.9,record:'9–8',percentile:'TOP 82%',title:'WINNING SEASON'},
 {min:1363.6,record:'8–9',percentile:'TOP 88%',title:'ON THE BUBBLE'},
 {min:1329.5,record:'7–10',percentile:'TOP 93%',title:'RETOOLING YEAR'},
 {min:1298.8,record:'6–11',percentile:'TOP 97%',title:'REBUILDING'},
 {min:1234.6,record:'5–12',percentile:'TOP 99%',title:'LOTTERY TEAM'},
 {min:-Infinity,record:'4–13',percentile:'BOTTOM 1%',title:'TOTAL REBUILD'},
];
function resultFor(value:number){return RECORD_LADDER.find(row=>value>=row.min)!}
function signed(value:number){return `${value>=0?'+':''}${value.toFixed(1)}`}

function eligible(label:string,p:Player){return label==='FLX'||label==='BENCH'?p.pos!=='QB':p.pos===label}
function randomPlayer(label:string){const pool=PLAYERS.filter(p=>eligible(label,p));return pool[Math.floor(Math.random()*pool.length)]}
function upgradePlayer(label:string,current:Player,pick:Pick){const cfg=PICK_CFG[pick];const upgrades=PLAYERS.filter(p=>eligible(label,p)&&p.points>current.points&&!(p.id===current.id&&p.year===current.year));if(!upgrades.length)return null;const desired=current.points+cfg.min+Math.pow(Math.random(),cfg.power)*(cfg.max-cfg.min);const capped=upgrades.filter(p=>p.points<=current.points+cfg.max);const pool=capped.length?capped:upgrades;return [...pool].sort((a,b)=>Math.abs(a.points-desired)-Math.abs(b.points-desired))[Math.floor(Math.random()*Math.min(8,pool.length))]}
function benchPlayer(pick:Pick){const pool=PLAYERS.filter(p=>p.pos!=='QB');const jackpot=Math.random();let quality:number;if(pick==='first')quality=jackpot<.13?Math.random()*35:35+Math.pow(Math.random(),.7)*65;else if(pick==='second')quality=jackpot<.08?85+Math.random()*15:15+Math.random()*70;else quality=jackpot<.035?88+Math.random()*12:Math.random()*58;const targetPct=100-quality;return [...pool].sort((a,b)=>Math.abs(a.percentile-targetPct)-Math.abs(b.percentile-targetPct))[Math.floor(Math.random()*Math.min(14,pool.length))]}
function Portrait({p,big=false}:{p:Player,big?:boolean}){return <div className={`portrait ${big?'big':''}`}><span>{p.name.split(' ').map(n=>n[0]).slice(-2).join('')}</span>{p.photo&&<img src={p.photo} alt={`${p.name} headshot`} loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.display='none'}}/>}</div>}

export default function Home(){
 const [slots,setSlots]=useState<Slot[]>(DEFAULT_SLOTS),[picks,setPicks]=useState<Record<Pick,boolean>>({first:true,second:true,third:true});
 const [active,setActive]=useState(0),[reveal,setReveal]=useState<Player|null>(null),[spinning,setSpinning]=useState(false),[pickTarget,setPickTarget]=useState<number|null>(null),[modal,setModal]=useState<'help'|'log'|null>(null),[hydrated,setHydrated]=useState(false),[statusNote,setStatusNote]=useState(''),[tradeHistory,setTradeHistory]=useState<Trade[]>([]);
 useEffect(()=>{try{const s=localStorage.getItem('dynasty-spin-royale-v3');if(s){const d=JSON.parse(s);setSlots(d.slots.map((slot:Slot)=>slot.player?{...slot,player:PLAYERS.find(p=>p.id===slot.player?.id&&p.year===slot.player?.year)||slot.player}:slot));setPicks(d.picks);setActive(d.active);setTradeHistory(d.tradeHistory||[])}}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem('dynasty-spin-royale-v3',JSON.stringify({slots,picks,active,tradeHistory}))},[slots,picks,active,tradeHistory,hydrated]);
 const total=useMemo(()=>slots.reduce((n,s)=>n+(s.player?.points||0),0),[slots]);const remainingCV=useMemo(()=>PICK_INFO.reduce((n,p)=>n+(picks[p.id]?p.value:0),0),[picks]);const franchiseValue=total+remainingCV;const result=resultFor(franchiseValue);const filled=slots.filter(s=>s.player).length;const next=slots.findIndex((s,i)=>i>=active&&!s.player&&!s.locked);const finished=filled===8;
 function animateTo(index:number,player:Player,pick?:Pick){setSpinning(true);setPickTarget(null);let ticks=0;const timer=setInterval(()=>{setReveal(randomPlayer(slots[index].label));if(++ticks>8){clearInterval(timer);setReveal(player);setTimeout(()=>{const old=slots[index].player;setSlots(prev=>prev.map((s,i)=>i===index?{...s,player,locked:false}:s));if(pick){setPicks(prev=>({...prev,[pick]:false}));const info=PICK_INFO.find(x=>x.id===pick)!;setTradeHistory(prev=>[{id:Date.now(),pickLabel:info.label,pickValue:info.value,outgoing:old,incoming:player,pointsDelta:+(player.points-(old?.points||0)).toFixed(1),cvDelta:player.value-(old?.value||0)-info.value},...prev])}setActive(Math.max(active,index+1));setSpinning(false)},520)}},62)}
 function freeSpin(index:number){animateTo(index,randomPlayer(slots[index].label))}
 function usePick(pick:Pick){if(pickTarget===null||!picks[pick])return;const current=slots[pickTarget].player;const player=current?upgradePlayer(slots[pickTarget].label,current,pick):benchPlayer(pick);if(!player){setStatusNote('That card is already the position ceiling—no pick can guarantee an upgrade.');setPickTarget(null);return}animateTo(pickTarget,player,pick)}
 function reset(){setSlots(DEFAULT_SLOTS);setPicks({first:true,second:true,third:true});setActive(0);setReveal(null);setPickTarget(null);setStatusNote('');setTradeHistory([]);localStorage.removeItem('dynasty-spin-royale-v3')}
 return <main className="game-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark"><img src="brand/dynasty-athletics-logo.png" alt="Dynasty Athletics logo"/></span><div><b>DYNASTY SPIN ROYALE</b><small>SPIN FOR THE CROWN</small></div></div><div className="season-tag"><span>4,000+ SEASONS</span> 1994—2024 · POSITION-ADJUSTED</div><nav><button onClick={()=>setModal('log')}>BUILD LOG</button><button className="icon-button" onClick={()=>setModal('help')} aria-label="How to play">?</button></nav></header>
  <section className="hero"><div><p className="eyebrow">YOUR FRANCHISE · ROUND 01</p><h1>Build your Dynasty.<br/><em>Spin for the Crown.</em></h1></div><div className="score-card"><span>{finished?'FRANCHISE VALUE':'TEAM SCORE'}</span><strong>{(finished?franchiseValue:total).toFixed(1)}</strong><small>{finished?`${total.toFixed(1)} PTS + ${remainingCV} CV`:'FANTASY PTS'}</small></div></section>
  {statusNote&&<button className="trade-note" onClick={()=>setStatusNote('')}><b>TRADE STATUS</b><span>{statusNote}</span><i>×</i></button>}
  {tradeHistory.length>0&&<section className="trade-history"><div className="trade-history-head"><div><p className="eyebrow">TRANSACTION LEDGER</p><h2>Trade History</h2></div><span>{tradeHistory.length} {tradeHistory.length===1?'TRADE':'TRADES'}</span></div>{tradeHistory.map(trade=><article key={trade.id}><div className="trade-route"><span className="trade-asset">{trade.outgoing?<><b>{trade.outgoing.year} {trade.outgoing.name}</b><small>{trade.outgoing.points} PTS · {trade.outgoing.value} CV</small></>:<><b>OPEN BENCH SPOT</b><small>0 PTS · 0 CV</small></>}</span><i>+</i><span className="trade-pick"><b>{trade.pickLabel} PICK</b><small>{trade.pickValue} CV</small></span><i>→</i><span className="trade-asset incoming"><b>{trade.incoming.year} {trade.incoming.name}</b><small>{trade.incoming.points} PTS · {trade.incoming.value} CV</small></span></div><div className="trade-return"><strong>{signed(trade.pointsDelta)} PTS</strong><span className={trade.cvDelta>=0?'positive':'negative'}>{signed(trade.cvDelta)} CV</span></div></article>)}</section>}
  {finished&&<section className="season-result"><div><p className="eyebrow">17-GAME RECORD</p><strong>{result.record}</strong><span>{result.title}</span></div><dl><div><dt>ROSTER</dt><dd>{total.toFixed(1)} PTS</dd></div><b>+</b><div><dt>UNSPENT PICKS</dt><dd>{remainingCV} CV</dd></div><b>=</b><div><dt>FRANCHISE VALUE</dt><dd>{franchiseValue.toFixed(1)}</dd></div></dl><em>{result.percentile} OF 100 DYNASTIES</em></section>}
  <section className="draft-board"><div className="board-head"><div><h2>Your Roster</h2></div><span>{filled} / 8 SPOTS FILLED</span></div><div className="roster-grid">{slots.map((s,i)=><article className={`roster-slot ${s.locked?'locked':''} ${s.player?s.player.tier:''}`} key={`${s.label}-${i}`}>{s.player?<><Portrait p={s.player}/><div className="card-top"><span className="position">{s.label}</span><span className="rarity-stack"><span className="rarity">{s.player.tier} · {s.player.percentile===0?'#1':`TOP ${Math.max(1,Math.ceil(s.player.percentile))}%`}</span><em>{s.player.value} CV</em></span></div><div className="player"><small>{s.player.year} · {s.player.team} · {s.player.pos}</small><h3>{s.player.name}</h3><div><strong>{s.player.points}</strong><span>PTS</span></div><button onClick={()=>setPickTarget(i)} disabled={!Object.values(picks).some(Boolean)}>TRADE PICK FOR RESPIN</button></div></>:<><span className="position">{s.label}</span><div className="empty-player"><span>{s.locked?'♛':'✦'}</span><b>{s.locked?'BENCH REEL LOCKED':'READY TO SPIN'}</b><small>{s.locked?'Wager a rookie pick to unlock':'Spin for a historic season'}</small>{s.locked&&<button onClick={()=>setPickTarget(i)}>WAGER A PICK</button>}</div></>}</article>)}</div></section>
  <section className="lower"><aside className="control-room"><div><p className="eyebrow">THE SPIN ROOM</p><h2>{finished?'The crown is yours':`Next reel: ${next>=0?slots[next].label:'BENCH'}`}</h2><p>{finished?'Your historic roster is complete. Is it a championship dynasty—or did the house win?':'Every free spin draws from 4,000+ qualifying seasons. Elite cards are true jackpot hits.'}</p></div><div className={`reel-preview ${reveal?.tier||''} ${spinning?'spinning':''}`}>{reveal?<><Portrait p={reveal} big/><small>{reveal.year} · {reveal.team} · {reveal.pos}</small><b>{reveal.name}</b><strong>{reveal.points} PTS · {reveal.value} CV</strong></>:<><span>♛</span><b>WHO’S HITTING<br/>THE NEXT REEL?</b></>}</div>{finished?<button className="spin-button ghost" onClick={reset}>PLAY AGAIN <span>↻</span></button>:<button className="spin-button" disabled={spinning||next<0} onClick={()=>freeSpin(next)}>{spinning?'REELS SPINNING…':`SPIN FOR ${next>=0?slots[next].label:'PLAYER'}`} <span>→</span></button>}</aside>
  <aside className="pick-bank"><div><p className="eyebrow">YOUR ROOKIE PICKS</p></div>{PICK_INFO.map(p=><button key={p.id} className={!picks[p.id]?'spent':''} disabled={!picks[p.id]} onClick={()=>setPickTarget(slots[7].locked?7:Math.max(0,active-1))}><b>{p.label}</b><small>{picks[p.id]?p.copy:'PICK TRADED'}</small><span>{picks[p.id]?`${p.value} CV`:'—'}</span><i>{picks[p.id]?p.range:''}</i></button>)}</aside></section>
  <section className="tier-key"><span>RARITY BY POSITION · TIES SHARE A TIER</span>{TIER_RANGES.map(t=><div key={t.tier} className={t.tier}><i></i><b>{t.tier}</b><small>{t.label}</small></div>)}</section>
  <footer><span>FULL PPR · 4PT PASS TD · DATA: NFLVERSE (CC-BY-4.0) · PLAYER PHOTOS: NFL + ESPN</span><button onClick={reset}>RESET FRANCHISE</button></footer>
  {pickTarget!==null&&<div className="overlay" onMouseDown={()=>setPickTarget(null)}><section className="pick-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setPickTarget(null)}>×</button><p className="eyebrow">THE HIGH-ROLLER TABLE</p><h2>{slots[pickTarget].locked?'Wager a pick on the bench':'Buy a guaranteed upgrade'}</h2><p>{slots[pickTarget].player?'Every pick guarantees more fantasy points than your current card. The round controls the upside; a small gain can still lose value against the wager.':'Your pick’s Chip Value (CV) unlocks the bench reel. The return can be worth more or less than your wager.'}</p><div>{PICK_INFO.map(p=><button key={p.id} disabled={!picks[p.id]||spinning} onClick={()=>usePick(p.id)}><span><b>{p.label} · {p.value} CV</b><small>{p.copy} {p.range}</small></span><strong>{picks[p.id]?'WAGER →':'TRADED'}</strong></button>)}</div></section></div>}
  {modal&&<div className="overlay" onMouseDown={()=>setModal(null)}><section className="info-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}>×</button>{modal==='help'?<><p className="eyebrow">HOUSE RULES</p><h2>How Spin Royale works</h2><ol><li><b>Take seven free spins.</b><span>Fill QB, two RBs, two WRs, TE, and FLX. Every 100+ point season can hit.</span></li><li><b>Read rarity by position.</b><span>A running back only competes with running backs. Tied scores always receive the same rarity.</span></li><li><b>Wager for guaranteed improvement.</b><span>Attaching any rookie pick guarantees a points gain. A 1st has the biggest ceiling; a 3rd has the smallest.</span></li><li><b>Price the risk.</b><span>Picks cost 100, 55, and 25 CV. Your roster improves even when the gain returns less value than the wager.</span></li><li><b>Unlock the bench reel.</b><span>Your eighth card requires a pick. Its CV can beat—or miss—the value of your wager.</span></li><li><b>Earn your record.</b><span>Final Franchise Value equals roster points plus every unspent pick’s CV. Your 17-game record is graded against 100 simulated completed teams; the top 5% finish 17–0.</span></li></ol></>:<><p className="eyebrow">BUILD LOG · V4.1</p><h2>Welcome to Spin Royale</h2><div className="log"><article><time>06 · DEEPER DATABASE</time><b>51 seasons became 4,000+</b><p>Regular-season stats from 1999–2024 create a real floor, middle class, and jackpot ceiling.</p></article><article><time>07 · POSITION RARITY</time><b>Every position gets its own curve</b><p>Ties share rarity. Bands land at 2%, 8%, 20%, 40%, 65%, and the remaining field.</p></article><article><time>08 · PICK VALUES</time><b>Rookie chips priced at 100 / 55 / 25 CV</b><p>Respins guarantee points gained, while return ranges preserve risk versus the wager.</p></article><article><time>09 · PLAYER IDENTITY</time><b>Historic cards carry headshots</b><p>Available licensed feed photography is paired with a clean initials fallback for older seasons.</p></article><article><time>10 · SPIN ROYALE</time><b>The casino floor opens</b><p>Reels, wagers, chips, jackpots, and a crown bring the fantasy casino floor to life.</p></article><article><time>11 · 100-SEASON CALIBRATION</time><b>Every finished team earns a record</b><p>One hundred complete rosters established a 1,225.2–2,429.9 Franchise Value history. The median landed at 1,607.9; 1,952.6 or higher earns a perfect 17–0.</p></article><article><time>12 · HISTORIC PHOTO AUDIT</time><b>227 missing players gained official cutouts</b><p>Exact-name NFL matches add transparent player imagery for many legends and veterans, while unmatched or questionable results keep the clean initials fallback.</p></article></div></>}</section></div>}
 </main>
}
