'use client';

import { useEffect, useMemo, useState } from 'react';

type Pos='QB'|'RB'|'WR'|'TE';
type Pick='first'|'second'|'third';
type Player={name:string;pos:Pos;year:number;team:string;passY?:number;passTD?:number;rushY?:number;rushTD?:number;rec?:number;recY?:number;recTD?:number;points?:number;percentile?:number;tier?:Tier};
type Tier='platinum'|'ruby'|'gold'|'emerald'|'silver'|'bronze';
type Slot={label:string;player:Player|null;locked?:boolean};

const RAW:Player[]=[
{name:'Steve Young',pos:'QB',year:1998,team:'SF',passY:4170,passTD:36,rushY:454,rushTD:6},{name:'Kurt Warner',pos:'QB',year:1999,team:'STL',passY:4353,passTD:41,rushY:60,rushTD:1},{name:'Daunte Culpepper',pos:'QB',year:2004,team:'MIN',passY:4717,passTD:39,rushY:406,rushTD:2},{name:'Peyton Manning',pos:'QB',year:2004,team:'IND',passY:4557,passTD:49,rushY:38,rushTD:0},{name:'Tom Brady',pos:'QB',year:2007,team:'NE',passY:4806,passTD:50,rushY:98,rushTD:2},{name:'Drew Brees',pos:'QB',year:2011,team:'NO',passY:5476,passTD:46,rushY:86,rushTD:1},{name:'Aaron Rodgers',pos:'QB',year:2011,team:'GB',passY:4643,passTD:45,rushY:257,rushTD:3},{name:'Cam Newton',pos:'QB',year:2015,team:'CAR',passY:3837,passTD:35,rushY:636,rushTD:10},{name:'Patrick Mahomes',pos:'QB',year:2018,team:'KC',passY:5097,passTD:50,rushY:272,rushTD:2},{name:'Lamar Jackson',pos:'QB',year:2019,team:'BAL',passY:3127,passTD:36,rushY:1206,rushTD:7},{name:'Josh Allen',pos:'QB',year:2020,team:'BUF',passY:4544,passTD:37,rushY:421,rushTD:8},{name:'Jalen Hurts',pos:'QB',year:2022,team:'PHI',passY:3701,passTD:22,rushY:760,rushTD:13},{name:'Jayden Daniels',pos:'QB',year:2024,team:'WAS',passY:3568,passTD:25,rushY:891,rushTD:6},
{name:'Barry Sanders',pos:'RB',year:1997,team:'DET',rushY:2053,rushTD:11,rec:33,recY:305,recTD:3},{name:'Terrell Davis',pos:'RB',year:1998,team:'DEN',rushY:2008,rushTD:21,rec:25,recY:217,recTD:2},{name:'Marshall Faulk',pos:'RB',year:2000,team:'STL',rushY:1359,rushTD:18,rec:81,recY:830,recTD:8},{name:'Priest Holmes',pos:'RB',year:2003,team:'KC',rushY:1420,rushTD:27,rec:74,recY:690,recTD:0},{name:'LaDainian Tomlinson',pos:'RB',year:2006,team:'SD',rushY:1815,rushTD:28,rec:56,recY:508,recTD:3},{name:'Adrian Peterson',pos:'RB',year:2012,team:'MIN',rushY:2097,rushTD:12,rec:40,recY:217,recTD:1},{name:'Jamaal Charles',pos:'RB',year:2013,team:'KC',rushY:1287,rushTD:12,rec:70,recY:693,recTD:7},{name:'David Johnson',pos:'RB',year:2016,team:'ARI',rushY:1239,rushTD:16,rec:80,recY:879,recTD:4},{name:'Todd Gurley',pos:'RB',year:2017,team:'LAR',rushY:1305,rushTD:13,rec:64,recY:788,recTD:6},{name:'Christian McCaffrey',pos:'RB',year:2019,team:'CAR',rushY:1387,rushTD:15,rec:116,recY:1005,recTD:4},{name:'Derrick Henry',pos:'RB',year:2020,team:'TEN',rushY:2027,rushTD:17,rec:19,recY:114,recTD:0},{name:'Jonathan Taylor',pos:'RB',year:2021,team:'IND',rushY:1811,rushTD:18,rec:40,recY:360,recTD:2},{name:'Austin Ekeler',pos:'RB',year:2022,team:'LAC',rushY:915,rushTD:13,rec:107,recY:722,recTD:5},{name:'Saquon Barkley',pos:'RB',year:2024,team:'PHI',rushY:2005,rushTD:13,rec:33,recY:278,recTD:2},
{name:'Jerry Rice',pos:'WR',year:1995,team:'SF',rec:122,recY:1848,recTD:15},{name:'Randy Moss',pos:'WR',year:2003,team:'MIN',rec:111,recY:1632,recTD:17},{name:'Marvin Harrison',pos:'WR',year:2002,team:'IND',rec:143,recY:1722,recTD:11},{name:'Terrell Owens',pos:'WR',year:2001,team:'SF',rec:93,recY:1412,recTD:16},{name:'Calvin Johnson',pos:'WR',year:2011,team:'DET',rec:96,recY:1681,recTD:16},{name:'Brandon Marshall',pos:'WR',year:2012,team:'CHI',rec:118,recY:1508,recTD:11},{name:'Demaryius Thomas',pos:'WR',year:2014,team:'DEN',rec:111,recY:1619,recTD:11},{name:'Antonio Brown',pos:'WR',year:2015,team:'PIT',rec:136,recY:1834,recTD:10},{name:'Julio Jones',pos:'WR',year:2015,team:'ATL',rec:136,recY:1871,recTD:8},{name:'Cooper Kupp',pos:'WR',year:2021,team:'LAR',rec:145,recY:1947,recTD:16},{name:'Davante Adams',pos:'WR',year:2020,team:'GB',rec:115,recY:1374,recTD:18},{name:'Justin Jefferson',pos:'WR',year:2022,team:'MIN',rec:128,recY:1809,recTD:8},{name:'Tyreek Hill',pos:'WR',year:2023,team:'MIA',rec:119,recY:1799,recTD:13},{name:"Ja'Marr Chase",pos:'WR',year:2024,team:'CIN',rec:127,recY:1708,recTD:17},
{name:'Ben Coates',pos:'TE',year:1994,team:'NE',rec:96,recY:1174,recTD:7},{name:'Shannon Sharpe',pos:'TE',year:1996,team:'DEN',rec:80,recY:1062,recTD:10},{name:'Tony Gonzalez',pos:'TE',year:2004,team:'KC',rec:102,recY:1258,recTD:7},{name:'Antonio Gates',pos:'TE',year:2005,team:'SD',rec:89,recY:1101,recTD:10},{name:'Rob Gronkowski',pos:'TE',year:2011,team:'NE',rec:90,recY:1327,recTD:17},{name:'Jimmy Graham',pos:'TE',year:2013,team:'NO',rec:86,recY:1215,recTD:16},{name:'Travis Kelce',pos:'TE',year:2020,team:'KC',rec:105,recY:1416,recTD:11},{name:'Mark Andrews',pos:'TE',year:2021,team:'BAL',rec:107,recY:1361,recTD:9},{name:'T.J. Hockenson',pos:'TE',year:2023,team:'MIN',rec:95,recY:960,recTD:5},{name:'Brock Bowers',pos:'TE',year:2024,team:'LV',rec:112,recY:1194,recTD:5}
];

function score(p:Player){return p.pos==='QB'?((p.passY||0)/25)+(p.passTD||0)*4+((p.rushY||0)/10)+(p.rushTD||0)*6:(p.rec||0)+((p.recY||0)+(p.rushY||0))/10+((p.recTD||0)+(p.rushTD||0))*6}
const PLAYERS=RAW.map(p=>({...p,points:+score(p).toFixed(1)})).map(p=>{const peers=RAW.filter(x=>x.pos===p.pos).map(score).sort((a,b)=>b-a);const rank=peers.findIndex(v=>v<=p.points!)+1;const pct=rank/peers.length*100;const tier:Tier=pct<=5?'platinum':pct<=8?'ruby':pct<=15?'gold':pct<=25?'emerald':pct<=50?'silver':'bronze';return {...p,percentile:+pct.toFixed(1),tier}}).filter(p=>p.points!>100);
const DEFAULT_SLOTS:Slot[]=['QB','RB','RB','WR','WR','TE','FLX','BENCH'].map(x=>({label:x,player:null,locked:x==='BENCH'}));
const PICK_INFO:{id:Pick;label:string;sub:string;odds:string}[]=[{id:'first',label:'1ST ROUND',sub:'Premium leverage',odds:'62% top-25% chance'},{id:'second',label:'2ND ROUND',sub:'Balanced gamble',odds:'34% top-25% chance'},{id:'third',label:'3RD ROUND',sub:'Long-shot ticket',odds:'16% top-25% chance'}];

function eligible(label:string,p:Player){return label==='FLX'||label==='BENCH'?p.pos!=='QB':p.pos===label}
function weightedPlayer(label:string,pick?:Pick,current?:Player|null){const pool=PLAYERS.filter(p=>eligible(label,p)&&!(current&&p.name===current.name&&p.year===current.year));if(!pick)return pool[Math.floor(Math.random()*pool.length)];const weight={first:{platinum:18,ruby:15,gold:11,emerald:8,silver:4,bronze:1},second:{platinum:7,ruby:7,gold:6,emerald:5,silver:4,bronze:3},third:{platinum:2,ruby:2,gold:2,emerald:3,silver:5,bronze:8}}[pick];const bag=pool.flatMap(p=>Array(weight[p.tier!]||1).fill(p));return bag[Math.floor(Math.random()*bag.length)]}

export default function Home(){
 const [slots,setSlots]=useState<Slot[]>(DEFAULT_SLOTS);const [picks,setPicks]=useState<Record<Pick,boolean>>({first:true,second:true,third:true});const [active,setActive]=useState(0);const [reveal,setReveal]=useState<Player|null>(null);const [spinning,setSpinning]=useState(false);const [pickTarget,setPickTarget]=useState<number|null>(null);const [modal,setModal]=useState<'help'|'log'|null>(null);const [hydrated,setHydrated]=useState(false);
 useEffect(()=>{try{const s=localStorage.getItem('dynasty-spin-v1');if(s){const d=JSON.parse(s);setSlots(d.slots);setPicks(d.picks);setActive(d.active)}}catch{}setHydrated(true)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem('dynasty-spin-v1',JSON.stringify({slots,picks,active}))},[slots,picks,active,hydrated]);
 const total=useMemo(()=>slots.reduce((n,s)=>n+(s.player?.points||0),0),[slots]);const filled=slots.filter(s=>s.player).length;const next=slots.findIndex((s,i)=>i>=active&&!s.player&&!s.locked);const finished=filled===8;
 function doSpin(index:number,pick?:Pick){if(spinning)return;if(pick&&!picks[pick])return;setSpinning(true);setPickTarget(null);let ticks=0;const timer=setInterval(()=>{setReveal(weightedPlayer(slots[index].label));ticks++;if(ticks>8){clearInterval(timer);const player=weightedPlayer(slots[index].label,pick,slots[index].player);setReveal(player);setTimeout(()=>{setSlots(old=>old.map((s,i)=>i===index?{...s,player,locked:false}:s));if(pick)setPicks(old=>({...old,[pick]:false}));setActive(Math.max(active,index+1));setSpinning(false)},550)}},70)}
 function usePick(pick:Pick){if(pickTarget===null)return;doSpin(pickTarget,pick)}
 function reset(){setSlots(DEFAULT_SLOTS);setPicks({first:true,second:true,third:true});setActive(0);setReveal(null);setPickTarget(null);localStorage.removeItem('dynasty-spin-v1')}
 return <main className="game-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark">D</span><div><b>DYNASTY SPIN</b><small>BUILD THE LEGACY</small></div></div><div className="season-tag"><span>1994—2024</span> HISTORIC PLAYER-SEASON POOL</div><nav><button onClick={()=>setModal('log')}>BUILD LOG</button><button className="icon-button" onClick={()=>setModal('help')} aria-label="How to play">?</button></nav></header>
  <section className="hero"><div><p className="eyebrow">YOUR FRANCHISE · YEAR 01</p><h1>Build a dynasty.<br/><em>Chase the crown.</em></h1></div><div className="score-card"><span>TEAM SCORE</span><strong>{total.toFixed(1)}</strong><small>FANTASY PTS</small></div></section>
  <section className="draft-board"><div className="board-head"><div><p className="eyebrow">STARTING LINEUP</p><h2>Your roster</h2></div><span>{filled} / 8 SLOTS FILLED</span></div><div className="roster-grid">{slots.map((s,i)=><article className={`roster-slot ${s.locked?'locked':''} ${s.player?s.player.tier:''}`} key={`${s.label}-${i}`}>{s.player?<><div className="card-top"><span className="position">{s.label}</span><span className="rarity">{s.player.tier}</span></div><div className="player"><small>{s.player.year} · {s.player.team} · {s.player.pos}</small><h3>{s.player.name}</h3><div><strong>{s.player.points}</strong><span>PTS</span></div><button onClick={()=>setPickTarget(i)} disabled={!Object.values(picks).some(Boolean)}>RESPIN WITH PICK</button></div></>:<><span className="position">{s.label}</span><div className="empty-player"><span>{s.locked?'◆':'+'}</span><b>{s.locked?'BENCH LOCKED':'EMPTY SLOT'}</b><small>{s.locked?'Trade any pick to unlock':'Spin to discover a season'}</small>{s.locked&&<button onClick={()=>setPickTarget(i)}>UNLOCK WITH PICK</button>}</div></>}</article>)}</div></section>
  <section className="lower"><aside className="control-room"><div><p className="eyebrow">PLAYER ACQUISITION</p><h2>{finished?'Dynasty complete':`On the clock: ${next>=0?slots[next].label:'BENCH'}`}</h2><p>{finished?'Your all-time roster is locked. How high did your franchise climb?':'Free roster spins are fully random. Picks can buy a weighted respin—or unlock your bench gamble.'}</p></div><div className={`reel-preview ${reveal?.tier||''} ${spinning?'spinning':''}`}>{reveal?<><small>{reveal.year} · {reveal.team} · {reveal.pos}</small><b>{reveal.name}</b><strong>{reveal.points} PTS</strong></>:<><span>?</span><b>WHO WILL DEFINE<br/>YOUR DYNASTY?</b></>}</div>{finished?<button className="spin-button ghost" onClick={reset}>START NEW DYNASTY <span>↻</span></button>:<button className="spin-button" disabled={spinning||next<0} onClick={()=>doSpin(next)}>{spinning?'SPINNING…':`SPIN FOR ${next>=0?slots[next].label:'PLAYER'}`} <span>→</span></button>}</aside>
  <aside className="pick-bank"><div><p className="eyebrow">FUTURE CAPITAL</p><h2>Rookie picks</h2></div>{PICK_INFO.map(p=><button key={p.id} className={!picks[p.id]?'spent':''} disabled={!picks[p.id]} onClick={()=>setPickTarget(pickTarget===null?(slots[7].locked?7:Math.max(0,active-1)):pickTarget)}><b>{p.label}</b><small>{picks[p.id]?p.sub:'PICK SPENT'}</small><span>{picks[p.id]?p.odds:'—'}</span></button>)}</aside></section>
  <section className="tier-key"><span>SEASON RARITY · POSITION-ADJUSTED</span>{(['platinum','ruby','gold','emerald','silver','bronze'] as Tier[]).map((t,i)=><div key={t} className={t}><i></i><b>{t}</b><small>{['TOP 5%','5—8%','8—15%','15—25%','25—50%','BOTTOM 50%'][i]}</small></div>)}</section>
  <footer><span>SCORING: FULL PPR · 4PT PASS TD · 0.04/PASS YD · 0.1/RUSH/REC YD</span><button onClick={reset}>RESET FRANCHISE</button></footer>
  {pickTarget!==null&&<div className="overlay" onMouseDown={()=>setPickTarget(null)}><section className="pick-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setPickTarget(null)}>×</button><p className="eyebrow">TRADE MARKET</p><h2>{slots[pickTarget].locked?'Unlock the bench':'Buy a respin'}</h2><p>Trade one future pick. Every result is a gamble, but premium picks shift the odds toward stronger position-adjusted seasons.</p><div>{PICK_INFO.map(p=><button key={p.id} disabled={!picks[p.id]||spinning} onClick={()=>usePick(p.id)}><span><b>{p.label}</b><small>{p.odds}</small></span><strong>{picks[p.id]?'TRADE →':'SPENT'}</strong></button>)}</div></section></div>}
  {modal&&<div className="overlay" onMouseDown={()=>setModal(null)}><section className="info-modal" onMouseDown={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)}>×</button>{modal==='help'?<><p className="eyebrow">FRONT OFFICE MANUAL</p><h2>How to build your dynasty</h2><ol><li><b>Spin the starters.</b><span>Fill QB, two RBs, two WRs, TE, and FLX for free. Each spin is random.</span></li><li><b>Spend picks strategically.</b><span>Your 1st, 2nd, and 3rd each buy one weighted respin. Better picks carry better odds—not guarantees.</span></li><li><b>Unlock the bench.</b><span>The eighth spot always costs one of your picks. Choose how much future capital to risk.</span></li><li><b>Chase the highest score.</b><span>Cards use the requested PPR scoring. Rarity compares each season against its position group.</span></li></ol></>:<><p className="eyebrow">BUILD LOG · V1.0</p><h2>From idea to kickoff</h2><div className="log"><article><time>01 · FOUNDATION</time><b>Rules translated into a playable loop</b><p>Eight roster slots, historic 100+ point seasons, and championship score chasing.</p></article><article><time>02 · SCORING ENGINE</time><b>Custom fantasy scoring applied</b><p>Full PPR, 4-point passing TDs, 6-point rushing/receiving TDs, and yardage rules.</p></article><article><time>03 · DYNASTY ECONOMY</time><b>Future picks became trade currency</b><p>One 1st, 2nd, and 3rd with increasingly volatile weighted return profiles.</p></article><article><time>04 · CARD SYSTEM</time><b>Six percentile rarity finishes</b><p>Platinum through bronze, position-adjusted so tight ends and running backs remain collectible.</p></article><article><time>05 · GAME FEEL</time><b>Persistent franchise board</b><p>Animated reveals, saved progress, responsive play, reset flow, and a complete-roster finale.</p></article></div></>}</section></div>}
 </main>
}
